steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/llm-backend:$COMMIT_SHA', '.']
    dir: 'LLM_BACKEND'
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/llm-backend:$COMMIT_SHA']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'llm-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/llm-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'PYTHONUNBUFFERED=1'
      - '--set-secrets'
      - 'GEMINI_API_KEY=gemini-api-key:latest,EXTERNAL_AI_KEY=external-ai-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/llm-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
